### ISSUE TITLE
bearer_token support

### ISSUE THREAD

**Issue by petersilva** [amacd31/kiwis_pie#5]
working on accessing Ontario Power Generation support, and they wrapped their instance in Azure authentication.
Outside of KIWIS, you need to log into a separate authentication service, and then issue a token request, and then supply the token to authorize WISKI access.  

I forked and got a simple fix for it... I added the ability to supply headers to the constructor, and include the bearer token in the header.  in my application code it looks like this:

```

     kheaders= { "Authorization" : f"Bearer {self.token}" }
     k = KIWIS(self.main_url, headers=kheaders )

```

And that seems to basically work.

**Comment by amacd31** [comment]
Included in release [0.10.4](https://pypi.org/project/kiwis-pie/0.10.4/)
